// Package publish turns a generated CLI into a managed GitHub repository with
// basic lifecycle files, git bootstrap, and an initial push.
package publish

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/disk0Dancer/climate/internal/githubutil"
	"github.com/disk0Dancer/climate/internal/manifest"
	"github.com/disk0Dancer/climate/internal/spec"
)

// Options controls how a generated CLI is published to GitHub.
type Options struct {
	Token         string
	Owner         string
	RepoName      string
	Description   string
	Homepage      string
	Visibility    string
	DefaultBranch string
	ReuseExisting bool
}

// Result describes the published repository state.
type Result struct {
	CLIName          string   `json:"cli_name"`
	SourceDir        string   `json:"source_dir"`
	Repository       string   `json:"repository"`
	RepositoryURL    string   `json:"repository_url"`
	RepositorySSHURL string   `json:"repository_ssh_url"`
	DefaultBranch    string   `json:"default_branch"`
	CreatedRepo      bool     `json:"created_repo"`
	LifecycleFiles   []string `json:"lifecycle_files"`
}

// ResolveToken returns the explicit token or a GitHub token from the environment.
func ResolveToken(explicit string) string {
	for _, candidate := range []string{
		explicit,
		os.Getenv("GITHUB_TOKEN"),
		os.Getenv("GH_TOKEN"),
	} {
		if strings.TrimSpace(candidate) != "" {
			return strings.TrimSpace(candidate)
		}
	}
	return ""
}

// Publish creates or reuses a GitHub repository, writes lifecycle files, and
// pushes the generated CLI source into that repository.
func Publish(ctx context.Context, entry manifest.CLIEntry, openAPI *spec.OpenAPI, opts Options) (*Result, error) {
	token := ResolveToken(opts.Token)
	if token == "" {
		return nil, fmt.Errorf("github token is required; set --github-token, GITHUB_TOKEN, or GH_TOKEN")
	}
	if entry.SourceDir == "" {
		return nil, fmt.Errorf("cli %q has no source directory recorded", entry.Name)
	}

	repoName := opts.RepoName
	if repoName == "" {
		repoName = entry.Name
	}
	branch := opts.DefaultBranch
	if branch == "" {
		branch = "main"
	}

	client := githubutil.NewClient(token)
	repo, created, err := client.EnsureRepository(ctx, githubutil.EnsureRepositoryRequest{
		Owner:         opts.Owner,
		Name:          repoName,
		Description:   repositoryDescription(entry.Name, openAPI, opts.Description),
		Homepage:      opts.Homepage,
		Private:       strings.EqualFold(opts.Visibility, "private"),
		ReuseExisting: opts.ReuseExisting,
	})
	if err != nil {
		return nil, err
	}
	if repo.DefaultBranch != "" {
		branch = repo.DefaultBranch
	}

	lifecycleFiles, err := EnsureLifecycleFiles(entry.SourceDir, ProjectMetadata{
		CLIName:       entry.Name,
		Repository:    repo.FullName,
		DefaultBranch: branch,
		OpenAPI:       openAPI,
	})
	if err != nil {
		return nil, err
	}

	if err := syncGitRepository(entry.SourceDir, repo, branch); err != nil {
		return nil, err
	}

	return &Result{
		CLIName:          entry.Name,
		SourceDir:        entry.SourceDir,
		Repository:       repo.FullName,
		RepositoryURL:    repo.HTMLURL,
		RepositorySSHURL: repo.SSHURL,
		DefaultBranch:    branch,
		CreatedRepo:      created,
		LifecycleFiles:   lifecycleFiles,
	}, nil
}

func repositoryDescription(cliName string, openAPI *spec.OpenAPI, explicit string) string {
	if strings.TrimSpace(explicit) != "" {
		return explicit
	}
	if openAPI == nil {
		return fmt.Sprintf("%s CLI generated by climate", cliName)
	}
	return fmt.Sprintf("%s CLI for %s, generated by climate", cliName, openAPI.Info.Title)
}

func syncGitRepository(sourceDir string, repo *githubutil.Repository, branch string) error {
	if err := os.MkdirAll(sourceDir, 0o755); err != nil {
		return fmt.Errorf("creating source dir: %w", err)
	}

	if _, err := os.Stat(filepath.Join(sourceDir, ".git")); os.IsNotExist(err) {
		if err := runGit(sourceDir, "init"); err != nil {
			return err
		}
	}

	if err := runGit(sourceDir, "branch", "-M", branch); err != nil {
		return err
	}

	remoteURL := repo.SSHURL
	if remoteURL == "" {
		remoteURL = repo.CloneURL
	}
	if remoteURL == "" {
		return fmt.Errorf("repository %s has no clone url", repo.FullName)
	}

	if err := ensureOriginRemote(sourceDir, remoteURL); err != nil {
		return err
	}

	if err := runGit(sourceDir, "add", "."); err != nil {
		return err
	}

	hasHead := runGit(sourceDir, "rev-parse", "--verify", "HEAD") == nil
	if !hasHead || hasStagedChanges(sourceDir) {
		if err := commitLifecycleBootstrap(sourceDir, repo.FullName); err != nil {
			return err
		}
	}

	if err := runGit(sourceDir, "push", "-u", "origin", branch); err != nil {
		return err
	}
	return nil
}

func hasStagedChanges(sourceDir string) bool {
	cmd := exec.Command("git", "diff", "--cached", "--quiet") //nolint:gosec
	cmd.Dir = sourceDir
	return cmd.Run() != nil
}

func ensureOriginRemote(sourceDir, remoteURL string) error {
	cmd := exec.Command("git", "remote", "get-url", "origin") //nolint:gosec
	cmd.Dir = sourceDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return runGit(sourceDir, "remote", "add", "origin", remoteURL)
	}
	if strings.TrimSpace(string(output)) == remoteURL {
		return nil
	}
	return runGit(sourceDir, "remote", "set-url", "origin", remoteURL)
}

func commitLifecycleBootstrap(sourceDir, repoFullName string) error {
	messagePath := filepath.Join(sourceDir, ".climate-git-commit.txt")
	defer func() {
		_ = os.Remove(messagePath)
	}()

	message := fmt.Sprintf(`Publish generated CLI as a managed GitHub project

Bootstrap repository automation and lifecycle files for %s.

Constraint: Generated CLI must remain buildable from standard Go toolchain without new dependencies
Rejected: Shelling out to gh for repo creation | runtime dependency outside the generated repository
Confidence: high
Scope-risk: narrow
Directive: Regenerate climate-managed files only when they still carry the climate marker
Tested: Git repository bootstrapped and initial push prepared
Not-tested: Remote release workflow execution
`, repoFullName)
	if err := os.WriteFile(messagePath, []byte(message), 0o644); err != nil {
		return fmt.Errorf("writing git commit message: %w", err)
	}
	return runGit(sourceDir, "commit", "-F", messagePath)
}

func runGit(dir string, args ...string) error {
	cmd := exec.Command("git", args...) //nolint:gosec
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("git %s: %w\n%s", strings.Join(args, " "), err, string(out))
	}
	return nil
}

// PublishedManifestEntry returns a manifest entry updated with repository metadata.
func PublishedManifestEntry(entry manifest.CLIEntry, result *Result) manifest.CLIEntry {
	entry.RepositoryURL = result.RepositoryURL
	entry.RepositoryFullName = result.Repository
	entry.RepositorySSHURL = result.RepositorySSHURL
	entry.RepositoryDefaultBranch = result.DefaultBranch
	entry.PublishedAt = time.Now()
	entry.LifecycleManaged = true
	return entry
}
