package publish

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/disk0Dancer/climate/internal/spec"
)

const (
	markdownManagedMarker = "<!-- Generated by climate publish. -->"
	textManagedMarker     = "# Generated by climate publish."
)

// ProjectMetadata drives repository bootstrap files.
type ProjectMetadata struct {
	CLIName       string
	Repository    string
	DefaultBranch string
	OpenAPI       *spec.OpenAPI
}

// EnsureLifecycleFiles creates or refreshes climate-managed repository files.
func EnsureLifecycleFiles(sourceDir string, meta ProjectMetadata) ([]string, error) {
	files := []struct {
		Path    string
		Marker  string
		Content string
	}{
		{Path: "README.md", Marker: markdownManagedMarker, Content: readmeContent(meta)},
		{Path: ".gitignore", Marker: textManagedMarker, Content: gitignoreContent()},
		{Path: filepath.Join(".github", "workflows", "ci.yml"), Marker: textManagedMarker, Content: ciWorkflowContent(meta)},
		{Path: filepath.Join(".github", "workflows", "release.yml"), Marker: textManagedMarker, Content: releaseWorkflowContent(meta)},
	}

	written := make([]string, 0, len(files))
	for _, file := range files {
		changed, err := writeManagedFile(filepath.Join(sourceDir, file.Path), file.Marker, file.Content)
		if err != nil {
			return nil, err
		}
		if changed {
			written = append(written, file.Path)
		}
	}
	sort.Strings(written)
	return written, nil
}

func writeManagedFile(path, marker, content string) (bool, error) {
	if data, err := os.ReadFile(path); err == nil {
		if !strings.Contains(string(data), marker) {
			return false, nil
		}
		if string(data) == content {
			return false, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("creating %s: %w", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}
	return true, nil
}

func readmeContent(meta ProjectMetadata) string {
	title := meta.CLIName
	description := fmt.Sprintf("%s is a generated CLI managed by climate.", meta.CLIName)
	usageHeading := "## Usage"
	if meta.OpenAPI != nil {
		title = meta.OpenAPI.Info.Title
		if strings.TrimSpace(meta.OpenAPI.Info.Description) != "" {
			description = meta.OpenAPI.Info.Description
		}
	}

	return fmt.Sprintf(`%s

# %s

%s

This repository was bootstrapped by climate from an OpenAPI specification and
is ready for CI, tagged releases, and GitHub-hosted lifecycle management.

## Install

~~~bash
go install github.com/%s@latest
~~~

%s

~~~bash
%s --help
%s <tag> <operation> --output=json
~~~

## Release

Push a tag like %s to trigger the release workflow:

~~~bash
git tag v0.1.0
git push origin v0.1.0
~~~
`, markdownManagedMarker, title, description, meta.Repository, usageHeading, meta.CLIName, meta.CLIName, "v0.1.0")
}

func gitignoreContent() string {
	return textManagedMarker + `
.DS_Store
coverage.out
dist/
*.exe
*.tar.gz
*.zip
`
}

func ciWorkflowContent(meta ProjectMetadata) string {
	return fmt.Sprintf(`%s
name: CI

on:
  push:
    branches: [%s]
  pull_request:
    branches: [%s]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run tests
        run: go test ./...

      - name: Build
        run: go build ./...
`, textManagedMarker, meta.DefaultBranch, meta.DefaultBranch)
}

func releaseWorkflowContent(meta ProjectMetadata) string {
	return fmt.Sprintf(`%s
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          EXT=""
          if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
          BINARY="%s-${GOOS}-${GOARCH}${EXT}"
          go build -ldflags="-X %s/cmd.version=${GITHUB_REF_NAME}" -o "${BINARY}" .
          echo "BINARY=${BINARY}" >> "$GITHUB_ENV"

      - name: Package binary
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip "%s-${{ matrix.goos }}-${{ matrix.goarch }}.zip" "${BINARY}"
            echo "ARCHIVE=%s-${{ matrix.goos }}-${{ matrix.goarch }}.zip" >> "$GITHUB_ENV"
          else
            tar czf "%s-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" "${BINARY}"
            echo "ARCHIVE=%s-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" >> "$GITHUB_ENV"
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE }}
`, textManagedMarker, meta.CLIName, meta.CLIName, meta.CLIName, meta.CLIName, meta.CLIName, meta.CLIName)
}
