package publish

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/disk0Dancer/climate/internal/spec"
)

const (
	markdownManagedMarker = "<!-- Generated by climate publish. -->"
	textManagedMarker     = "# Generated by climate publish."
)

// ProjectMetadata drives repository bootstrap files.
type ProjectMetadata struct {
	CLIName       string
	Repository    string
	DefaultBranch string
	OpenAPI       *spec.OpenAPI
}

// EnsureLifecycleFiles creates or refreshes climate-managed repository files.
func EnsureLifecycleFiles(sourceDir string, meta ProjectMetadata) ([]string, error) {
	files := []struct {
		Path    string
		Marker  string
		Content string
	}{
		{Path: "README.md", Marker: markdownManagedMarker, Content: readmeContent(meta)},
		{Path: ".gitignore", Marker: textManagedMarker, Content: gitignoreContent()},
		{Path: ".golangci.yml", Marker: textManagedMarker, Content: golangciContent()},
		{Path: filepath.Join(".github", "workflows", "ci.yml"), Marker: textManagedMarker, Content: ciWorkflowContent(meta)},
		{Path: filepath.Join(".github", "workflows", "ci-autofix.yml"), Marker: textManagedMarker, Content: ciAutofixWorkflowContent(meta)},
		{Path: filepath.Join(".github", "workflows", "release.yml"), Marker: textManagedMarker, Content: releaseWorkflowContent(meta)},
	}

	written := make([]string, 0, len(files))
	for _, file := range files {
		changed, err := writeManagedFile(filepath.Join(sourceDir, file.Path), file.Marker, file.Content)
		if err != nil {
			return nil, err
		}
		if changed {
			written = append(written, file.Path)
		}
	}
	sort.Strings(written)
	return written, nil
}

func writeManagedFile(path, marker, content string) (bool, error) {
	if data, err := os.ReadFile(path); err == nil {
		if !strings.Contains(string(data), marker) {
			return false, nil
		}
		if string(data) == content {
			return false, nil
		}
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, fmt.Errorf("creating %s: %w", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return false, fmt.Errorf("writing %s: %w", path, err)
	}
	return true, nil
}

func readmeContent(meta ProjectMetadata) string {
	title := meta.CLIName
	description := ""
	if meta.OpenAPI != nil {
		if meta.OpenAPI.Info.Title != "" {
			title = meta.OpenAPI.Info.Title
		}
		if d := strings.TrimSpace(meta.OpenAPI.Info.Description); d != "" {
			description = d
		}
	}

	// Count endpoints
	endpointCount := 0
	if meta.OpenAPI != nil {
		for _, pi := range meta.OpenAPI.Paths {
			endpointCount += len(pi.Operations())
		}
	}

	stats := ""
	if endpointCount > 0 {
		stats = fmt.Sprintf(" · %d endpoints", endpointCount)
	}

	// Subtitle line
	subtitle := fmt.Sprintf("Generated Go CLI for %s%s", title, stats)
	if description != "" && description != title {
		subtitle = fmt.Sprintf("%s%s", description, stats)
	}

	// Command groups from tags
	var groups string
	if meta.OpenAPI != nil && len(meta.OpenAPI.Tags) > 0 {
		names := make([]string, 0, len(meta.OpenAPI.Tags))
		for _, t := range meta.OpenAPI.Tags {
			names = append(names, t.Name)
		}
		groups = fmt.Sprintf(`
## Commands

~~~
%s
~~~
`, strings.Join(names, ", "))
	}

	// Owner
	owner := ""
	if parts := strings.SplitN(meta.Repository, "/", 2); len(parts) == 2 {
		owner = parts[0]
	}

	return fmt.Sprintf(`%s

# %s

%s

## Install

~~~bash
go install github.com/%s@latest
~~~

## Usage

~~~bash
%s --help
%s <group> <operation> [flags]
~~~
%s
## About

Built with [climate](https://github.com/disk0Dancer/climate) — any API becomes a tool.

~~~bash
brew tap disk0Dancer/tap && brew install climate
climate generate --name %s <spec-url>
~~~

---

[@%s](https://github.com/%s) · [climate](https://github.com/disk0Dancer/climate)
`, markdownManagedMarker, meta.CLIName, subtitle,
		meta.Repository,
		meta.CLIName, meta.CLIName,
		groups,
		meta.CLIName,
		owner, owner)
}

func gitignoreContent() string {
	return textManagedMarker + `
.DS_Store
coverage.out
dist/
*.exe
*.tar.gz
*.zip
`
}

func golangciContent() string {
	return textManagedMarker + `
version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - unused
`
}

func ciWorkflowContent(meta ProjectMetadata) string {
	return fmt.Sprintf(`%s
name: CI

on:
  push:
    branches: [%s]
  pull_request:
    branches: [%s]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Check formatting
        run: |
          unformatted="$(gofmt -l .)"
          if [ -n "$unformatted" ]; then
            echo "These files are not gofmt-formatted:"
            echo "$unformatted"
            exit 1
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.3

      - name: Run tests
        run: go test ./...

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build ./...
`, textManagedMarker, meta.DefaultBranch, meta.DefaultBranch)
}

func ciAutofixWorkflowContent(meta ProjectMetadata) string {
	return fmt.Sprintf(`%s
name: CI Auto-Fix

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

permissions:
  contents: write
  actions: write

concurrency:
  group: ci-autofix-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  autofix:
    if: >
      github.event.workflow_run.conclusion == 'failure' &&
      github.event.workflow_run.head_repository.full_name == github.repository &&
      github.event.workflow_run.head_branch != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout failed branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Stop on stale branch head
        id: freshness
        run: |
          current_sha="$(git rev-parse HEAD)"
          expected_sha="${{ github.event.workflow_run.head_sha }}"
          if [ "$current_sha" != "$expected_sha" ]; then
            echo "should_skip=true" >> "$GITHUB_OUTPUT"
            echo "Branch advanced from ${expected_sha} to ${current_sha}; skipping stale auto-fix run."
            exit 0
          fi
          echo "should_skip=false" >> "$GITHUB_OUTPUT"

      - name: Set up Go
        if: steps.freshness.outputs.should_skip != 'true'
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        if: steps.freshness.outputs.should_skip != 'true'
        run: go mod download

      - name: Run gofmt auto-fix
        if: steps.freshness.outputs.should_skip != 'true'
        run: gofmt -w .

      - name: Run golangci-lint auto-fix
        id: golangci_autofix
        if: steps.freshness.outputs.should_skip != 'true'
        continue-on-error: true
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.11.3
          args: --fix

      - name: Detect changes
        id: changes
        if: steps.freshness.outputs.should_skip != 'true'
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No auto-fixable changes detected."
            exit 0
          fi
          echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Commit and push auto-fixes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "ci: auto-fix formatting and lint"
          git push origin HEAD:${{ github.event.workflow_run.head_branch }}

      - name: Re-dispatch CI
        if: steps.changes.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          curl --fail --silent --show-error \
            -X POST \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci.yml/dispatches \
            -d '{"ref":"${{ github.event.workflow_run.head_branch }}"}'
`, textManagedMarker)
}

func releaseWorkflowContent(meta ProjectMetadata) string {
	return fmt.Sprintf(`%s
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          EXT=""
          if [ "$GOOS" = "windows" ]; then EXT=".exe"; fi
          BINARY="%s-${GOOS}-${GOARCH}${EXT}"
          go build -ldflags="-X %s/cmd.version=${GITHUB_REF_NAME}" -o "${BINARY}" .
          echo "BINARY=${BINARY}" >> "$GITHUB_ENV"

      - name: Package binary
        run: |
          if [ "${{ matrix.goos }}" = "windows" ]; then
            zip "%s-${{ matrix.goos }}-${{ matrix.goarch }}.zip" "${BINARY}"
            echo "ARCHIVE=%s-${{ matrix.goos }}-${{ matrix.goarch }}.zip" >> "$GITHUB_ENV"
          else
            tar czf "%s-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" "${BINARY}"
            echo "ARCHIVE=%s-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz" >> "$GITHUB_ENV"
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ARCHIVE }}
`, textManagedMarker, meta.CLIName, meta.CLIName, meta.CLIName, meta.CLIName, meta.CLIName, meta.CLIName)
}
