package commands

import (
	"github.com/disk0Dancer/climate/internal/manifest"
	"github.com/spf13/cobra"
)

var listCmd = &cobra.Command{
	Use:   "list",
	Short: "List all generated CLIs",
	Long:  `List all CLIs previously generated by climate.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		mf, err := manifest.Load()
		if err != nil {
			exitError("Failed to load manifest", err)
		}

		type listResp struct {
			CLIs []manifest.CLIEntry `json:"clis"`
		}
		writeJSON(listResp{CLIs: mf.List()})
		return nil
	},
}

func init() {
	rootCmd.AddCommand(listCmd)
}
